### ISSUE TITLE
[Qustaion] can replace OpenSSL with WolfSSL?

### ISSUE THREAD

**Issue by mokhtarabadi** [chux0519/pegasocks#14]
It is possible?

The difference just is the final execution file size, a simple library with static linking OpenSSL is about 4-5Mb but with WolfSSL is about 500-700 Kb
This will be important In Android because Android not have shared OpenSSL and need to link it statically

**Comment by chux0519** [comment]
OpenSSL is used for 

- vmess encode/decode (libcrypto, this can be replaced with wolfcrypt)
- libevent's `bufferevent_ssl.h` (libssl, this maybe replaced when libevent 2.2 is published, see: https://github.com/libevent/libevent/issues/1016)

so yeah, I think it's possible

There is another possible choice I think, the `mbedtls`，which is already supported by libevent, but I've never used mbedtls or WolfSSL, I always prefer the lighter one.

**Comment by chux0519** [comment]
@mokhtarabadi  Hi, I added support for mbedtls(v2.27), use [feat-mbedtls](https://github.com/chux0519/pegasocks/tree/feat-mbedtls)  to see if this reduce your binary size on Android.

**Comment by mokhtarabadi** [comment]
Hi @chux0519 , thanks
i will test it tomorrow and share the results

**Comment by mokhtarabadi** [comment]
I failed after trying many attempts to build pegasocks for Android :(
I created this bash script for doing that https://github.com/mokhtarabadi/pegasocks-android
only success command is `./build.sh arm 21` when using OpenSSL
if try run for other architectures, for example `arm64`, the script failed because `libcrypto.a` need `libdl` but also did not work after adding this in `CMakeFiles.txt`
and if want to use MbedTLS, the script failed because the linker wants to link MbedTLS libraries in both modes (shared,static)
can you check the script and fix the problems?

Thank you

**Comment by chux0519** [comment]
@mokhtarabadi I take a look and found out that the mbedtls libs have some sort of dependencies:

mbedtls -> mbedx509 -> mbedcrypto

I correct them, and remove the `-lpthread` flag on android, try the latest master branch, it should work, and it seems the final static linked pegas is 1M+

**Comment by mokhtarabadi** [comment]
I updated the script...
now all targets are built with MbedTLS, and the final size difference is about ~576Kb (mean APK file), but before I used [prebuilt OpenSSL libraries](https://github.com/leenjewel/openssl_for_ios_and_android) maybe this can affect the binary size! (i need to test more)

one thing more, when I run the command like `./build.sh arm64 21 OFF` (mean using OpenSSL) I see errors about linking libdl, but when I change target to `arm` all things work, can you help me to fix them?
I edit the CMake files and insert `dl` but no success

**Comment by chux0519** [comment]
> I updated the script...
> now all targets are built with MbedTLS, and the final size difference is about ~576Kb (mean APK file), but before I used [prebuilt OpenSSL libraries](https://github.com/leenjewel/openssl_for_ios_and_android) maybe this can affect the binary size! (i need to test more)
> 
> one thing more, when I run the command like `./build.sh arm64 21 OFF` (mean using OpenSSL) I see errors about linking libdl, but when I change target to `arm` all things work, can you help me to fix them?
> I edit the CMake files and insert `dl` but no success

I'm not very familiar with Android, according to https://github.com/android/ndk/issues/472, it seems that libdl is just a placeholder on Android, and I disable the [DSO](https://github.com/openssl/openssl/blob/master/INSTALL.md#no-dso) by this:

```
@@ -101,6 +101,7 @@ build_openssl() {

       # build
       android_cmake_command \
+            -DDSO_NONE=ON \
             -DBUILD_SHARED_LIBS=OFF \
             -DWITH_APPS=OFF \
             ..
```

And it compiles

**Comment by mokhtarabadi** [comment]
> > I updated the script...
> > now all targets are built with MbedTLS, and the final size difference is about ~576Kb (mean APK file), but before I used [prebuilt OpenSSL libraries](https://github.com/leenjewel/openssl_for_ios_and_android) maybe this can affect the binary size! (i need to test more)
> > one thing more, when I run the command like `./build.sh arm64 21 OFF` (mean using OpenSSL) I see errors about linking libdl, but when I change target to `arm` all things work, can you help me to fix them?
> > I edit the CMake files and insert `dl` but no success
> 
> I'm not very familiar with Android, according to [android/ndk#472](https://github.com/android/ndk/issues/472), it seems that libdl is just a placeholder on Android, and I disable the [DSO](https://github.com/openssl/openssl/blob/master/INSTALL.md#no-dso) by this:
> 
> ```
> @@ -101,6 +101,7 @@ build_openssl() {
> 
>        # build
>        android_cmake_command \
> +            -DDSO_NONE=ON \
>              -DBUILD_SHARED_LIBS=OFF \
>              -DWITH_APPS=OFF \
>              ..
> ```
> 
> And it compiles

Thanks, now everything works, the size difference for arm64 is about 705KB in the APK file
Also, I'm not familiar with low-level languages

**Comment by mokhtarabadi** [comment]
Hi @chux0519,
I want to add `jemalloc` support to android builds but failed, for example,`./build.sh arm 16 ON ON` failed due to multiple definitions when linking, if you have free time please take a look

**Comment by chux0519** [comment]
> Hi @chux0519,
> I want to add `jemalloc` support to android builds but failed, for example,`./build.sh arm 16 ON ON` failed due to multiple definitions when linking, if you have free time please take a look

I guess Android libc's malloc is using jemalloc already, so it hit the `multiple definitions`, and I searched these page you can have a look

- https://stackoverflow.com/questions/2266762/android-libc-version-and-malloc-implementation
- https://source.android.com/devices/tech/debug/scudo (this indicates the allocator will change in Android 11)
- https://android.googlesource.com/platform/external/jemalloc (this is the jemalloc from android.googlesource)

I think use the default allocator is just OK.

**Comment by mokhtarabadi** [comment]
So I can remove jemalloc, this is a question for me why google not used [their own malloc](https://github.com/google/tcmalloc)
